name: a2c
agent: a2c
meta_objective: null
gamma_metal: null
lambda_metal: null
l_pg_metal: null
l_td_metal: null
l_en_metal: null
gamma_outer: null
lambda_outer: null
l_pg_outer: null
l_td_outer: null
l_en_outer: null
l_kl_outer: null
bootstrap_l: null
bootstrap_pm: null
bootstrap_vm: null
meta_optimizer: null
meta_learning_rate: null
meta_gradient_clip_norm: null
bootstrap_l_optimizer: null
bootstrap_l_learning_rate: null
